---
openapi: 3.0.3
info:
  title: Personal data
  description: Example API spec for pyconpl2020 workshop
  version: 1.0.0
paths:
  /api/person/:
    get:
      description: Get the list of persons
      operationId: personList
      responses:
        '200':
          description: The list of persons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
    post:
      description: Create a person
      operationId: createPerson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
        required: true
      responses:
        '200':
          description: Created a person
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        '400':
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonError'

components:
  schemas:
    Person:
      type: object
      required:
        - id
        - firstName
        - gender
        - lastName
      properties:
        id:
          type: integer
          readOnly: true
        first_name:
          type: string
          minLength: 2
          maxLength: 128
          nullable: false
        last_name:
          type: string
          minLength: 2
          maxLength: 128
          nullable: false
        gender:
          type: string
          enum: 
            - 'M'
            - 'F'
        birthdate:
          type: string
          format: date
    PersonError:
      type: object
      properties:
        message:
          type: string
